### ISSUE TITLE
Ошибки при регистрации и удалении

### ISSUE THREAD

**Issue by zaqwer101** [zaqwer101/Organizer_API#19]
```
app_1            | 172.22.0.6 - - [08/Oct/2020 09:46:47] "POST /register HTTP/1.0" 500 -
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
app_1            |     return self.wsgi_app(environ, start_response)
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
app_1            |     response = self.handle_exception(e)
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
app_1            |     reraise(exc_type, exc_value, tb)
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
app_1            |     raise value
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
app_1            |     response = self.full_dispatch_request()
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
app_1            |     rv = self.handle_user_exception(e)
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
app_1            |     reraise(exc_type, exc_value, tb)
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
app_1            |     raise value
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
app_1            |     rv = self.dispatch_request()
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
app_1            |     return self.view_functions[rule.endpoint](**req.view_args)
app_1            |   File "/api/api.py", line 28, in check_params_inner
app_1            |     return func(*args, **kwargs)
app_1            |   File "/api/api.py", line 187, in register
app_1            |     return error(r.json()['error'], 400)
app_1            | KeyError: 'error'
```

```
app_1            | 172.22.0.6 - - [08/Oct/2020 09:47:51] "DELETE /shoplist HTTP/1.0" 500 -
app_1            | Traceback (most recent call last):
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2464, in __call__
app_1            |     return self.wsgi_app(environ, start_response)
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2450, in wsgi_app
app_1            |     response = self.handle_exception(e)
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1867, in handle_exception
app_1            |     reraise(exc_type, exc_value, tb)
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
app_1            |     raise value
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 2447, in wsgi_app
app_1            |     response = self.full_dispatch_request()
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1952, in full_dispatch_request
app_1            |     rv = self.handle_user_exception(e)
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1821, in handle_user_exception
app_1            |     reraise(exc_type, exc_value, tb)
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/_compat.py", line 39, in reraise
app_1            |     raise value
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1950, in full_dispatch_request
app_1            |     rv = self.dispatch_request()
app_1            |   File "/usr/local/lib/python3.9/site-packages/flask/app.py", line 1936, in dispatch_request
app_1            |     return self.view_functions[rule.endpoint](**req.view_args)
app_1            |   File "/api/api.py", line 67, in check_auth
app_1            |     return func(*args, **kwargs)
app_1            |   File "/api/api.py", line 22, in check_params_inner
app_1            |     if not param in request.get_json().keys():
app_1            | AttributeError: 'NoneType' object has no attribute 'keys'
```

**Comment by zaqwer101** [comment]
В 93fc358f724f02b5419dba761be6173dc1843b91 починил регистрацию

**Comment by zaqwer101** [comment]
Автотесты проходят, значит всё работает, закрываю
